source 'https://rubygems.org'

gem 'chunky_png'
gem 'exifr'
gem 'nokogiri'
gem 'rest-client'
gem 'rubyzip'
gem 'pcap', :git => 'https://github.com/ahobson/ruby-pcap'
gem 'whois'
gem 'therubyracer'
gem 'rmagick', '~>2.13.2'
